### ISSUE TITLE
qual é a melhor forma de contatá-lo?

### ISSUE THREAD

**Issue by ghost** [santosgv/Login.mvc.sqlAlquimist#2]
Oi @santosgv, como está?

Vi no seu perfil que há um link de referência ao Twitter, LinkedIn, Whatsapp. Mas qual é a melhor forma de contatá-lo?  você utiliza o Twitter, LinkedIn ou Whatsapp ainda para comunicar-se?

ps: seus projetos de código aberto são excelentes. Pergunto-me sobre isso, pois gostaria de saber como posso seguir você no sentido de acompanhar possíveis projetos abertos aos quais você pode optar por ajudar, contribuir, colaborar ou não.  Você prefere que eu abra uma issue no GitHub sobre os bugs? envie por e-mail? ou faça tweets sobre minhas dúvidas ou possíveis sugestões de melhoria do código? 

att,
solarsbeans.

**Comment by santosgv** [comment]
Ola ! vou bem. pode me seguir na qual voce achar melhor. sobre contribuir
tambem pode me chamar tanto no linkedln quanto no Twitter.

Em ter., 5 de set. de 2023 às 10:46, Solarbeans ***@***.***>
escreveu:
